# Generated by Django 3.1.3 on 2022-06-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_auto_20220608_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='full_time',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='learner',
            name='social_link',
            field=models.URLField(blank=True),
        ),
    ]
